"""
ui/pages/report_page.py
PPT Report generation page — one-click executive presentation.
"""

from __future__ import annotations

import json

import streamlit as st

from ai.prompt_builder import build_insight_prompt
from analytics.stats_engine import (
    compute_correlation,
    compute_kpis,
    detect_all_outliers,
)
from config.settings import CONFIG, get_groq_api_key
from reports.ppt_generator import ReportInput, generate_ppt_report


def _get_ai_insights(df, profile, metric_col: str) -> dict | None:
    """Try to get AI narrative. Returns None on any failure — report still works."""
    api_key = get_groq_api_key()
    if not api_key:
        return None
    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        prompt = build_insight_prompt(df, profile, metric_col)
        response = client.chat.completions.create(
            model=CONFIG.ai.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=800,
        )
        raw = response.choices[0].message.content
        # Strip markdown fences if present
        clean = raw.strip()
        if "```json" in clean:
            clean = clean.split("```json")[1].split("```")[0].strip()
        elif "```" in clean:
            clean = clean.split("```")[1].split("```")[0].strip()
        return json.loads(clean)
    except Exception as e:
        st.caption(f"AI insights unavailable: {e}")
        return None


def render() -> None:
    st.header("📋 Generate PPT Report")
    st.caption(
        "Auto-generate a professional PowerPoint presentation from your analysis. "
        "Includes data overview, KPIs, statistics, outliers, and AI insights."
    )

    load_result = st.session_state.load_result
    profile = st.session_state.profile
    clean_result = st.session_state.clean_result

    if profile is None:
        st.warning("Upload a file first.")
        return

    df = clean_result.df if clean_result else load_result.df

    # ── Report configuration ──────────────────────────────────────
    st.subheader("Report Settings")

    col1, col2 = st.columns(2)
    with col1:
        metric_col = st.selectbox(
            "Primary metric for KPI slide",
            options=profile.numeric_columns if profile.has_numeric else ["—"],
            key="report_metric_col",
        )
    with col2:
        date_col = st.selectbox(
            "Date column (for MoM trend)",
            options=["None", *profile.datetime_columns],
            key="report_date_col",
        )
        date_col = None if date_col == "None" else date_col

    include_ai = st.checkbox(
        "Include AI-generated insights slide",
        value=True,
        help="Requires GROQ_API_KEY to be configured. Skipped gracefully if not available.",
    )

    # ── Preview what will be included ────────────────────────────
    with st.expander("📋 Report will include these slides", expanded=True):
        slides = [
            ("✅", "Title Slide", f"Dataset: {load_result.file_name}"),
            (
                "✅",
                "Data Overview",
                f"{profile.total_rows:,} rows, {profile.total_columns} cols, quality {profile.quality_score}/100",
            ),
            (
                "✅" if profile.has_numeric else "⏭️",
                "KPI Summary",
                f"Primary metric: {metric_col}",
            ),
            (
                "✅" if profile.has_numeric else "⏭️",
                "Statistical Summary",
                "Descriptive stats for all numeric columns",
            ),
            (
                "✅" if profile.has_numeric else "⏭️",
                "Outlier Analysis",
                "IQR-based outlier detection per column",
            ),
            (
                "✅" if (profile.has_numeric and len(profile.numeric_columns) >= 2) else "⏭️",
                "Key Correlations",
                "Pearson correlation coefficient (r) between numeric columns",
            ),
            (
                "✅" if include_ai else "⏭️",
                "AI Insights",
                "Narrative + 3 key findings + recommendation",
            ),
            ("✅", "Closing Slide", "Generated by Excel Auto-Analyst"),
        ]
        for icon, title, desc in slides:
            st.write(f"{icon} **{title}** — {desc}")

    st.divider()

    # ── Generate button ───────────────────────────────────────────
    if st.button("🎯 Generate PPT Report", type="primary", use_container_width=True):
        progress = st.progress(0, text="Preparing data...")

        try:
            # Step 1: KPI
            progress.progress(15, "Computing KPIs...")
            kpi = None
            if profile.has_numeric and metric_col and metric_col != "—":
                try:
                    kpi = compute_kpis(df, metric_col, date_col)
                except Exception as e:
                    st.caption(f"KPI computation skipped: {e}")

            # Step 2: Outliers
            progress.progress(35, "Detecting outliers...")
            outliers = {}
            if profile.has_numeric:
                try:
                    outliers = detect_all_outliers(df, profile)
                except Exception as e:
                    st.caption(f"Outlier detection skipped: {e}")

            # Step 3: Correlation
            progress.progress(50, "Computing correlations...")
            correlation = None
            if len(profile.numeric_columns) >= 2:
                try:
                    correlation = compute_correlation(df, profile)
                except Exception as e:
                    st.caption(f"Correlation skipped: {e}")

            # Step 4: AI Insights
            progress.progress(65, "Generating AI insights...")
            ai_insights = None
            if include_ai and profile.has_numeric and metric_col and metric_col != "—":
                ai_insights = _get_ai_insights(df, profile, metric_col)

            # Step 5: Build PPT
            progress.progress(80, "Building PowerPoint...")
            report_input = ReportInput(
                df=df,
                profile=profile,
                kpi=kpi,
                outliers=outliers,
                correlation=correlation,
                ai_insights=ai_insights,
                file_name=load_result.file_name,
                metric_col=metric_col
                if metric_col != "—"
                else (profile.numeric_columns[0] if profile.numeric_columns else "N/A"),
            )
            ppt_bytes = generate_ppt_report(report_input)
            progress.progress(100, "Done!")

        except Exception as e:
            progress.empty()
            st.error(f"Report generation failed: {type(e).__name__}: {e}")
            return

        progress.empty()
        st.success("✅ Report generated successfully!")

        # ── Download button ────────────────────────────────────────
        report_filename = (
            f"analysis_report_{load_result.file_name.rsplit('.', 1)[0]}.pptx"
        )
        st.download_button(
            label="⬇️  Download PowerPoint Report",
            data=ppt_bytes,
            file_name=report_filename,
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
            use_container_width=True,
        )

        st.balloons()

        # ── Summary of what's in the report ───────────────────────
        st.subheader("Report Contents Summary")
        c1, c2, c3 = st.columns(3)
        c1.metric("Slides Generated", "8")
        c2.metric("Columns Analysed", len(profile.numeric_columns))
        c3.metric("AI Insights", "Included" if ai_insights else "Skipped (no API key)")
